### ISSUE TITLE
Compability with KP 2.52 - Dev. 221205 (64-bit)

### ISSUE THREAD

**Issue by backbone10** [ihanson/KeePass-Rule-Builder#16]
Hi, for me it looks like as the latest version is not compatible with 2.52 - Dev. 221205 (64-bit). It does not start after compilation, it complains compbility issue. Can you pls check. Thanks in advance !

**Comment by ihanson** [comment]
If you’re building KeePass yourself from source instead of using the [standard download](https://keepass.info/download.html) from the KeePass website, you need to also build the Rule Builder plugin from source, referencing the version of `KeePass.exe` that you built.

**Comment by backbone10** [comment]
I just installed Keepass 2.53, and now it works fine, thx !
