### ISSUE TITLE
Feature Request: Minimum Instances of a Character Set

### ISSUE THREAD

**Issue by brogers5** [ihanson/KeePass-Rule-Builder#18]
I just had to set up an account which, among other password requirements, had a requirement for at least 6 lowercase characters.

As far as I know, marking a given Character Set as Required will only guarantee at least 1 instance of the Character Set within the resulting password. This could theoretically result in a non-compliant password being generated if other Character Sets are also included and selected.

I would like to be able to configure a Rule that complies with this without needing to resort to workarounds, such as regenerating, increasing the password length, or manually padding the resulting password.

**Comment by ihanson** [comment]
You can list multiple copies of the same character set as required, and then it will always generate passwords with at least that many characters from the character set.

<img src="https://github.com/ihanson/KeePass-Rule-Builder/assets/755453/3d397d64-a944-429a-8f55-4e48ac949ad0" height="477.8" width="389.3" alt="Rule with six duplicate copies of the “Lowercase letters” character set, all required">

**Comment by brogers5** [comment]
Didn't realize I could duplicate character set entries. Just tested it out and this is behaving as expected. Thanks!
