### ISSUE TITLE
Change Password - Update the "Expires"-Field

### ISSUE THREAD

**Issue by Timo-1979** [ihanson/KeePass-Rule-Builder#3]
I want to change a password of an account, where I've got to change the password every month.

In this case I use your dialog "Generate new password...", but this has no option to update the "expires"-Field. For this I've got to open the Entry in the normal way and that I've got to update this field.

I think it would be nice to have an option to update this field in one step with changing the password.
And it would be great, if the last uses time-period could be stored in the entry.

I've created a mock for the "new" Generate-Password-Dialog - see Attachement.

![Change-Password](https://user-images.githubusercontent.com/43135977/97144205-54189e00-1764-11eb-9e5f-7f858b61510f.png)

On the left side the period could be choosen (it would be nice if this value could be save for this entry) and on the right side the calculated date will be displayed and could be modified (This valuwill be stored in to the entry "expires"-field). The "update"-button on right side should set the date to: today + the selected period.

**Comment by ihanson** [comment]
This feature is added in the [Version 3.0](https://github.com/ihanson/KeePass-Rule-Builder/releases/tag/v3.0) release. Thanks for the suggestion!
