### ISSUE TITLE
Entry Expiry Status Not Cleared

### ISSUE THREAD

**Issue by corrigami** [ihanson/KeePass-Rule-Builder#6]
Running KeePass 2.48.1 (64 bit, Portable) with v3.0.0.0 of the plugin, I've tried to update a password of an expired entry using the 'Generate New Password...' option. 

The password is changed successfully and the expiry date is set correctly. 

The issue is that the entry is still shown as expired with a X over the icon and strikethrough font. To clear the expiration status, I had to open the entry and then press OK.

Linked to: https://github.com/ihanson/KeePass-Rule-Builder/issues/3#issue-729316428

**Comment by ihanson** [comment]
This is now fixed in the [Version 3.1](https://github.com/ihanson/KeePass-Rule-Builder/releases/tag/v3.1) release. Thanks!
