### ISSUE TITLE
Feature request: expand password length

### ISSUE THREAD

**Issue by vmXeon** [ihanson/KeePass-Rule-Builder#7]
Hi, I'm using your RuleBuilder plugin. And it's fantastic!

But I have some problems with the plugin. Is it possible to make password length longer? When using RuleBuilder window it's restricted to 99 chars max. But some of my passwords are longer and it's impossible to define rule for them. 

It is easy to solve the problem using field editing: "just change the value "Length" in "Password Rule" field". But when I define password rule for a whole entry group -- it's impossible to edit this property manually.

Please make it possible to define password length longer than 99 chars. Thanks!

**Comment by vmXeon** [comment]
ADD.
I tried to solve the problem by myself. I have a several entries for one website (let's say example.com) and I want to define **one** password rule for them. But they are stored in different groups. Subsequently, it's impossible to define the one rule for them all using "Group Password Rule" function.

I tried to use KeePass references. I defined a special entry (for example, "Example.com Password Rule"), filled it's "Notes" field with "Password Rule" definition for RuleBuilder. And pasted a KeePass reference to the entry's "Notes" field in all of my "example.com" entries. It didn't work. Is it possbile to use KeePass references with RuleBuilder?

**Comment by ihanson** [comment]
For both of those scenarios, I would suggest using a profile instead of a rule. You can [define a profile](https://keepass.info/help/base/pwgenerator.html#profiles) that produces a password longer than 99 characters, and you can link an entry to a profile using the Rule Builder so that new passwords for that entry will be generated from that profile.

**Comment by vmXeon** [comment]
Thanks for your answer.

Yes, it is possible solution. But in a case of different PC's with different KeePass installations it's inconvenient. I have to sync password profile between KeePass installations manually. Maybe portable version will help, but I'm not sure about different OS (for example, KeePass for Win on my Home PC, and KeePass Mono on Ubuntu Work Laptop).

Suggestion in my [previous message](https://github.com/ihanson/KeePass-Rule-Builder/issues/7#issuecomment-903599287) allows to define password rule as a part of KeePass Database. And consequently, the password rule becomes portable.

Anyway, thank you! For your answer, and for your work!
