### ISSUE TITLE
Default profile

### ISSUE THREAD

**Issue by havalo-lolawo** [ihanson/KeePass-Rule-Builder#8]
Any chance of having the option to select the default profile to use when generating a new password instead of manually selecting it?

**Comment by ihanson** [comment]
You can do that by setting the password rule to the desired profile in the top-level group in the password database. You can also [modify the “Automatically generated password for new entries” profile](https://keepass.info/help/base/pwgenerator.html#configauto) that KeePass uses by default when creating an entry.
